# Generated by Django 4.2.4 on 2023-12-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
