# Generated by Django 4.2.4 on 2023-12-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurants_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
