# Generated by Django 4.2.4 on 2023-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurants_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='category',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg'), ('Both', 'Both')], max_length=100, null=True),
        ),
    ]
