# Generated by Django 4.2.4 on 2023-12-31 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_alter_restaurants_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='category',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg'), ('Both', 'Both')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
