# Generated by Django 4.2.4 on 2024-01-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurants_contact_info_restaurants_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='menu',
        ),
    ]
